# Generated by Django 5.2.7 on 2025-11-25 23:15

import diagrams.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def populate_projects(apps, schema_editor):
    Project = apps.get_model('diagrams', 'Project')
    ProjectMembership = apps.get_model('diagrams', 'ProjectMembership')
    now = timezone.now()

    Project.objects.filter(created_at__isnull=True).update(
        created_at=now,
        updated_at=now,
    )

    for project in Project.objects.all():
        ProjectMembership.objects.get_or_create(
            project=project,
            user=project.user,
            defaults={'role': 'owner'},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagram',
            old_name='type',
            new_name='diagram_type',
        ),
        migrations.AlterField(
            model_name='diagram',
            name='diagram_type',
            field=models.CharField(choices=[('bpmn', 'BPMN'), ('dfd', 'DFD'), ('erd', 'ERD')], default='bpmn', max_length=10),
        ),
        migrations.AddField(
            model_name='diagram',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=diagrams.models.generate_invite_token, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='diagrams.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='diagrams.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.RunPython(populate_projects, migrations.RunPython.noop),
    ]
