# Generated by Django 5.2.7 on 2025-12-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0002_remove_diagram_type_diagram_diagram_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_element_id', models.CharField(max_length=100)),
                ('source_element_label', models.CharField(blank=True, default='', max_length=255)),
                ('target_element_id', models.CharField(blank=True, max_length=100, null=True)),
                ('link_type', models.CharField(choices=[('reference', 'Reference'), ('decomposition', 'Decomposition'), ('implementation', 'Implementation'), ('data_source', 'Data Source')], default='reference', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_links', to=settings.AUTH_USER_MODEL)),
                ('source_diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='diagrams.diagram')),
                ('target_diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='diagrams.diagram')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('source_diagram', 'source_element_id', 'target_diagram')},
            },
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
