# Generated by Django 5.2.7 on 2025-12-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0003_diagramlink_delete_relation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diagramlink',
            unique_together=set(),
        ),
    ]
